services:
  - type: web
    name: football-injury-predictor
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      mkdir -p ~/.streamlit
      cp setup.sh ~/.streamlit/config.toml
      streamlit run app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PORT
        value: 8501 