services:
  - type: web
    name: football-injury-predictor
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python train_model.py
    startCommand: streamlit run app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 8501 